---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/offices":
    post:
      summary: Creates an office
      tags:
      - Offices
      parameters: []
      responses:
        '201':
          description: office created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                area:
                  type: string
                occupancy:
                  type: number
                images:
                  type: string
                basic_price:
                  type: number
                address:
                  type: string
              required:
              - title
              - description
              - area
              - occupancy
              - images
              - basic_price
              - address
    get:
      summary: Retrieves all offices list
      tags:
      - Offices
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: http://127.0.0.1:4000/api/v1
